apiVersion: v1
entries:
  kafka:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-06T17:33:27.109953+05:30
    description: A Helm chart for Kubernetes
    digest: 678a621151ecf27726e1357242cdc8b47fa2ecfc44fb99b2513aaa0f985b6e57
    name: kafka
    urls:
    - https://github.com/srishti-gajare/helm-test.git/helm/kafka/kafka-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-06T17:33:27.10915+05:30
